#:schema node_modules/wrangler/config-schema.json
name = "bsky-bot-recalls"
main = "src/index.ts"
compatibility_date = "2024-11-30"
compatibility_flags = ["nodejs_compat_v2"]

# Variable bindings.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
[vars]
BSKY_USERNAME = 'CF_DEV'

# Docs: https://developers.cloudflare.com/workflows/
[[workflows]]
name = "fda-workflow"
binding = "WORKFLOW_FDA"
class_name = "FdaWorkflow"

# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "recall-alert-prod"
database_id = "e14fe74a-668b-42eb-86da-37beda02a487"
migrations_dir = "drizzle/migrations"
preview_database_id = "DB"                           # should match binding name

# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["*/30 * * * *"] # every 30 minutes
[env.dev.triggers]
crons = ["* * * * *"] # every minute

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
