// Generated by Wrangler by running `wrangler types src/env.d.ts`

interface Env {
	BSKY_USERNAME: "CF_PROD";
	API_URL: "https://bsky-bot-recalls.jumpwindstudio.workers.dev";
	BSKY_PASSWORD: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_DATABASE_ID: string;
	DB: D1Database;
	API: Fetcher;
}
